[package]
name = "chuchi-postgres-types"
description = "Common types when working with Postgres in Rust"
version = "0.1.0"
authors = ["Sören Meier <info@soerenmeier.ch>"]
homepage = "https://chuchi.dev/"
repository = "https://github.com/chuchi-dev/chuchi-postgres"
edition = "2021"
license = "MIT OR Apache-2.0"
# only for default features and serde, json, postgres
rust-version = "1.67"

[features]
serde = ["dep:serde"]
json = ["dep:postgres-types", "postgres-types?/with-serde_json-1"]
# todo this will be replaced with some other crate that fire
protobuf = ["dep:protopuffer"]
juniper = ["dep:juniper"]
postgres = ["dep:postgres-types"]

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
chrono = "0.4.30"
protopuffer = { version = "0.1", optional = true }
juniper = { version = "0.16", default-features = false, optional = true }
base64 = "0.22"
rand = "0.8"
postgres-types = { version = "0.2", optional = true }
bytes = "1.6.0"
postgres-protocol = "0.6.6"

[dev-dependencies]
serde_json = "1.0"
